default_stages: [push, commit]
minimum_pre_commit_version: 2.10.1

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: black
        name: run black
        entry: black
        types: [python]
        language: system
        stages: [push, commit]

      - id: flake8
        name: run flake8
        entry: flake8
        types: [python]
        language: system
        stages: [push, commit]

      - id: mypy
        name: run mypy
        entry: mypy . --exclude venv --explicit-package-bases -V
        types: [python]
        language: system
        stages: [push, commit]
