name: Docker CI and Pre-commit

on:
  push:
    branches:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: run pre-commit
        run: |
          pip install pre-commit black mypy flake8
          pre-commit run --all-files

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2

      - name: set up docker
        run: docker-compose up -d --build

      - name: stop docker compose
        run: docker-compose down