name: Docker CI and Pre-commit

on:
  push:
    branches:
      - '*'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: run pre-commit
        run: |
          pip install pre-commit black mypy flake8 fastapi
          pre-commit run --all-files

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: create env file
        run: echo "${{ secrets.ENV_FILE }}" > src/.env

      - name: set up docker
        run: docker-compose up -d --build

      - name: pytest
        run: docker-compose exec web pytest .

      - name: black
        run: black .

      - name: mypy
        run: mypy . --exclude venv

      - name: flake8
        run: flake8 --exclude venv

      - name: stop docker compose
        run: docker-compose down